# Generated by Django 2.2.10 on 2020-10-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200913_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, default='C:/Users/elnar/PyCharmProjects/TrialDj/static_in_env/img/product/product-1.jpg', null=True, upload_to='C:/Users/elnar/PyCharmProjects/TrialDj/static_in_env/img/db_img/'),
        ),
    ]
