# Generated by Django 2.2.10 on 2020-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201004_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, default='C:/Users/elnar/PyCharmProjects/TrialDj/static_in_env/img/product/product-1.jpg', upload_to='db_img/'),
        ),
    ]
